C
C     K1     - beginning times of detailed storms
C     K2     - ending times of detailed storms
C     NF     - number of storms in the sequence of days
C              containing storm
C     NFS    - starting CORF-minute intervals for storms
C     POBS   - measured rainfall volumes for storm events
C     TESTNO - objective function flag
C              0 - do not include storm
C              1 - include storm
C     BFL    - base flow
C     FPK    - measured peaks, cfs
C     FVOL   - measured volumes, inches
C     NDATE  - storm dates: (1) month, (2) day, (3) year
C     NHOUR  - storm start time, military
