C
      INTEGER   MXST, MXRG, MXDX, MXSG, MXDT, MXST2
      PARAMETER ( MXST = 60, MXRG = 3, MXDX = 10, MXSG = 99 )
      PARAMETER ( MXST2 = 2*MXST )
      PARAMETER ( MXDT = 1441 )
C
C     MXST   - maximum number of storms
C     MXRG   - maximum number of rain gages
C     MXDX   - maximum number of dx per segment
C     MXSG   - maximum number of segments
C     MXDT   - maximum number of dt per storm
