C     version information: versn = char*64
      VERSN = '@(#)DR3M -- Distributed Routing Rainfall-Runoff Model'
      VERSN = '@(#)DR3M --  Vers. II'
      VERSN = '@(#)DR3M -- USGS OFR 82-344, Alley and Smith'
      VERSN = '@(#)DR3M -- Contact Kate Flynn, kmflynn@usgs.gov'
      VERSN = '@(#)DR3M -- Version 2.0 1994/05/01 (HASS tape 2)'
      VERSN = '@(#)DR3M -- Version 2.1 1996/03/01 (HASS tape 3)'
